development:
  adapter: postgresql
  encoding: utf8
  database: weight_trackr_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: weight_trackr_test
  pool: 5 

production:
  adapter: postgresql
  encoding: utf8
  database: weight_trackr_app
  pool: 5 